### ISSUE TITLE
There are some C examples in the Python part of OLED library tutorial

### ISSUE THREAD

**Issue by CelineBoudier** [OnionIoT/wiki#1]
In https://wiki.onion.io/Tutorials/Libraries/OLED-Expansion-Library.
For instance, some (but not all) of the lines have semicolons at the end (it works but it's not pythonic)
Worse: "int status;" which won't execute.

**Comment by greenbreakfast** [comment]
Ah it was pretty late at night when I was working on the examples, should be all fixed now!
Thanks for the tip and feel free the let us know about any further improvements we can make
