### ISSUE TITLE
Arduino-duck script is not found !

### ISSUE THREAD

**Issue by yaseenox-personal** [OnionIoT/wiki#16]
Hi, when trying to run the following command:
sh /usr/bin/arduino-dock flash bootloader
to flash the bootloader to the duck I get this message:
sh: can't open '/usr/bin/arduino-dock'

**Comment by greenbreakfast** [comment]
Ah, the `arduino-dock` package is no longer automatically installed on the Omega, try running the following command to install the package:

```
opkg update
opkg install arduino-dock
```

Then try again and let me know how it goes!
(I've updated the Arduino Dock wiki articles to note this as well)

**Comment by yaseenox-personal** [comment]
Hi,

Thanks everything works fine now, but I am getting this message in the arduino IDE :
merge-sketch-with-bootloader.lua
when uploading the sketch to the omega, however the sketch worked.

Regards,
yaseen

**Comment by greenbreakfast** [comment]
glad it worked out.
you can ignore the `merge-sketch-with-bootloader.lua` message, the upload will work either way :)
